version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python3 app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ../.env.example
    depends_on:
      - db
      - migration

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migration
    depends_on:
      - db
    env_file:
      - ../.env.example

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    env_file:
      - ../.env.example

volumes:
  postgres_data:
