version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - migration

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile.migration
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/home/code/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
